# Embeddings

EMBEDDING_MODEL_NAME = "BAAI/bge-large-en-v1.5"
EMBEDDING_DIMENSION = 1024

# Qdrant

COLLECTION_NAME = "neet_biology"

# Retrieval

TOP_K_RETRIEVAL = 20
FINAL_CONTEXT_K = 5

# Similarity

MIN_SIMILARITY_SCORE = 0.60

PARENT_WORD_LIMIT = 375
CHILD_WORD_LIMIT = 115
CHILD_OVERLAP = 25

EMBEDDING_BATCH_SIZE = 32